name: Code Checks

on:
  push:
    branches: [ master ]

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: ESLint And TSC
      run: npm run eslint
